/**
* o------------------------------------------------------------------------------o
* | This file is part of the RGraph package - you can learn more at:             |
* |                                                                              |
* |                          http://www.rgraph.net                               |
* |                                                                              |
* | This package is licensed under the RGraph license. For all kinds of business |
* | purposes there is a small one-time licensing fee to pay and for non          |
* | commercial  purposes it is free to use. You can read the full license here:  |
* |                                                                              |
* |                      http://www.rgraph.net/LICENSE.txt                       |
* o------------------------------------------------------------------------------o
*/

if(typeof RGraph=="undefined")RGraph={};RGraph.Registry={};RGraph.Registry.store=[];RGraph.background={};RGraph.objects=[];
RGraph.getScale=function(a){if(a==0)return["0.2","0.4","0.6","0.8","1.0"];var b=a;if(a<=1)if(a>0.5)return[0.2,0.4,0.6,0.8,Number(1).toFixed(1)];else if(a>=0.1)return[0.1,0.2,0.3,0.4,0.5];else{var c=a;for(b=0;c<1.01;){b+=1;c*=10}c=["2e-"+b,"4e-"+b,"6e-"+b,"8e-"+b,"10e-"+b];if(a<="5e-"+b)c=["1e-"+b,"2e-"+b,"3e-"+b,"4e-"+b,"5e-"+b];return c}if(String(a).indexOf(".")>0)a=String(a).replace(/\.\d+$/,"");for(var f=c=Math.pow(10,Number(String(Number(a)).length-1));f<a;)f+=c/2;if(Number(b)>Number(f))f+=c/
2;if(a<10)f=Number(b)<=5?5:10;return[f*0.2,f*0.4,f*0.6,f*0.8,f]};RGraph.array_max=function(a,b){for(var c=null,f=0;f<a.length;++f)c=c?Math.max(c,b?Math.abs(a[f]):a[f]):a[f];return c};RGraph.array_sum=function(a){if(typeof a=="number")return a;var b,c,f=a.length;for(c=b=0;b<f;c+=a[b++]);return c};RGraph.degrees2Radians=function(a){return a*(Math.PI/180)};RGraph.lineByAngle=function(a,b,c,f,d){a.arc(b,c,d,f,f,false);a.lineTo(b,c);a.arc(b,c,d,f,f,false)};
RGraph.Text=function(a,b,c,f,d,e,g,h,k,l,n,m){if(document.all)d+=2;a.font=(m?"Bold ":"")+c+"pt "+b;b=a.fillStyle;if(typeof g==null)g="bottom";if(typeof h==null)h="left";if(typeof k==null)k=null;if(typeof l==null)l=0;if(navigator.userAgent.indexOf("Opera")!=-1){a.canvas.__rgraph_valign__=g;a.canvas.__rgraph_halign__=h}a.save();a.canvas.__rgraph_originalx__=f;a.canvas.__rgraph_originaly__=d;a.translate(f,d);d=f=0;l&&a.rotate(l/57.3);if(g){l=g;if(l=="center")a.translate(0,c/2);else l=="top"&&a.translate(0,
c)}if(h){m=h;l=a.measureText(e).width;if(m)if(m=="center")a.translate(-1*(l/2),0);else m=="right"&&a.translate(-1*l,0)}if(n){m=document.all?2:0;l=a.measureText(e).width;a.strokeStyle="gray";a.fillStyle=n;a.fillRect(f-3,d-c-3-m,l+6,c+6);a.strokeRect(f-3,d-c-3-m,l+6,c+6)}a.fillStyle=b;a.save();a.fillText(e,0,0);if(k){l=a.measureText(e).width;a.translate(f,d);a.strokeRect(0,0,l,0-c);a.fillRect(h=="left"?0:(h=="center"?l/2:l)-2,g=="bottom"?0:(g=="center"?(0-c)/2:0-c)-2,4,4)}a.restore();a.restore()};
RGraph.Clear=function(a,b){var c=a.width;a.width=c;if(b){context=a.getContext("2d");context.beginPath();context.fillStyle=String(b);context.fillRect(0,0,c,a.height);context.fill()}RGraph.ClearAnnotations(a.id)};
RGraph.DrawTitle=function(a,b,c,f,d){var e=a.__object__,g=a.getContext("2d");d=d?d:12;a=f?f:a.width/2;var h=e.Get("chart.key.position");f=c/2;if(e.type=="bar"&&e.Get("chart.variant")=="3d")h="gutter";g.beginPath();g.fillStyle=e.Get("chart.text.color")?e.Get("chart.text.color"):"black";h=h&&h!="gutter"?"center":h?"bottom":"center";if(typeof e.Get("chart.title.vpos")=="number")f=e.Get("chart.title.vpos")*c;if(typeof(e.Get("chart.title.color")!=null)){var k=g.fillStyle;g.fillStyle=e.Get("chart.title.color")}c=
e.Get("chart.text.font");RGraph.Text(g,c,d,a,f,b,h,"center",null,null,null,true);g.fillStyle=k};RGraph.getMouseXY=function(a){var b=document.all?a.srcElement:a.target,c,f;if(typeof a.offsetX=="number"&&typeof a.offsetY=="number"){c=a.offsetX;f=a.offsetY}else{for(f=c=0;b!=document.body;){c+=b.offsetLeft;f+=b.offsetTop;b=b.offsetParent}c=a.pageX-c;f=a.pageY-f}return[c,f]};RGraph.getCanvasXY=function(a){var b=0,c=0;for(a=a;a!=document.body;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return[b,c]};
RGraph.Tooltip=function(a,b,c,f){var d=RGraph.Registry.Get("chart.tooltip.timers");if(d&&d.length)for(h=0;h<d.length;++h)clearTimeout(d[h]);RGraph.Registry.Set("chart.tooltip.timers",[]);RGraph.HideContext();RGraph.Redraw(a.id);if(RGraph.Registry.Get("chart.tooltip")){RGraph.Registry.Get("chart.tooltip").style.display="none";RGraph.Registry.Set("chart.tooltip",null)}RGraph.HideContext();if(d=/^id:(.*)/.exec(b))b=document.getElementById(d[1]).innerHTML;d=document.createElement("DIV");d.className="RGraph_tooltip";
d.style.display="none";d.style.position="absolute";d.style.left=0;d.style.top=0;d.style.backgroundColor="#ffe";d.style.color="black";if(!document.all)d.style.border="1px solid rgba(0,0,0,0)";d.style.visibility="visible";d.style.paddingLeft="3px";d.style.paddingRight="3px";d.style.fontFamily="Tahoma";d.style.fontSize="10pt";d.style.zIndex=3;d.style.borderRadius="5px";d.style.MozBorderRadius="5px";d.style.WebkitBorderRadius="5px";d.style.WebkitBoxShadow="rgba(96,96,96,0.5) 3px 3px 3px";d.style.MozBoxShadow=
"rgba(96,96,96,0.5) 3px 3px 3px";d.style.boxShadow="rgba(96,96,96,0.5) 3px 3px 3px";d.style.filter="progid:DXImageTransform.Microsoft.Shadow(color=#666666,direction=135)";d.style.opacity=0;d.style.overflow="hidden";d.innerHTML=b;d.__text__=b;d.style.display="inline";document.body.appendChild(d);b=d.offsetWidth;h=d.offsetHeight;d.style.width=b+"px";if(c+b>document.body.offsetWidth){c=c-b-7;f=f;var e=true;d.style.left=c+"px";d.style.top=f+"px"}else{c+=5;d.style.left=c+"px";d.style.top=f-h+"px"}var g=
a.__object__.Get("chart.tooltip.effect");if(g=="expand"){d.style.left=c+b/2+"px";d.style.top=f-h/2+"px";leftDelta=b/2/10;topDelta=h/2/10;d.style.width=0;d.style.height=0;d.style.boxShadow="";d.style.MozBoxShadow="";d.style.WebkitBoxShadow="";d.style.borderRadius=0;d.style.MozBorderRadius=0;d.style.WebkitBorderRadius=0;d.style.opacity=1;RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",
25));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",50));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",75));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",
100));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",125));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",150));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",
175));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",200));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",225));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.left = (parseInt(RGraph.Registry.Get('chart.tooltip').style.left) - leftDelta) + 'px' }",
250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",25));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",50));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",
75));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",100));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",125));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",
150));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",175));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",200));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",
225));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.top = (parseInt(RGraph.Registry.Get('chart.tooltip').style.top) - topDelta) + 'px' }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.1+"px'; }",25));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+
b*0.2+"px'; }",50));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.3+"px'; }",75));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.4+"px'; }",100));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+
b*0.5+"px'; }",125));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.6+"px'; }",150));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.7+"px'; }",175));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+
b*0.8+"px'; }",200));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b*0.9+"px'; }",225));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.width = '"+b+"px'; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+
h*0.1+"px'; }",25));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.2+"px'; }",50));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.3+"px'; }",75));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+
h*0.4+"px'; }",100));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.5+"px'; }",125));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.6+"px'; }",150));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+
h*0.7+"px'; }",175));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.8+"px'; }",200));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+h*0.9+"px'; }",225));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.height = '"+
h+"px'; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').innerHTML = RGraph.Registry.Get('chart.tooltip').__text__; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.boxShadow = 'rgba(96,96,96,0.5) 3px 3px 3px'; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.MozBoxShadow = 'rgba(96,96,96,0.5) 3px 3px 3px'; }",
250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.WebkitBoxShadow = 'rgba(96,96,96,0.5) 3px 3px 3px'; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.borderRadius = '5px'; }",250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.MozBorderRadius = '5px'; }",
250));RGraph.Registry.Get("chart.tooltip.timers").push(setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.WebkitBorderRadius = '5px'; }",250))}else if(e&&g=="fade")d.style.top=f-h+"px";else g!="fade"&&g!="expand"&&alert("[COMMON] Unknown tooltip effect: "+g);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.1; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",
25);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.2; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",50);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.3; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",75);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.4; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",
100);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.5; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",125);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.6; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.2)'; }",150);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.7; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.4)'; }",
175);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.8; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.6)'; }",200);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 0.9; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgba(96,96,96,0.8)'; }",225);setTimeout("if (RGraph.Registry.Get('chart.tooltip')) { RGraph.Registry.Get('chart.tooltip').style.opacity = 1; RGraph.Registry.Get('chart.tooltip').style.border = '1px solid rgb(96,96,96'; }",
250);document.body.onmousedown=function(){var k=RGraph.Registry.Get("chart.tooltip");if(k){k.style.display="none";k.style.visibility="hidden";RGraph.Registry.Set("chart.tooltip",null);RGraph.Redraw()}};c=d.getElementsByTagName("a");for(var h=0;h<c.length;++h)c[h].onmousedown=function(k){location.href=this.href;k.cancelBubble=true;k.stopPropagation();return false};window.onresize=function(){var k=RGraph.Registry.Get("chart.tooltip");if(k){k.style.display="none";k.style.visibility="hidden";RGraph.Registry.Set("chart.tooltip",
null);RGraph.Clear(a);a.__object__.Draw()}};RGraph.Registry.Set("chart.tooltip",d)};RGraph.Register=function(a){RGraph.objects[a.id+"_"+a.type]=a};RGraph.Redraw=function(a){for(i in RGraph.objects)if(typeof i=="string"&&typeof RGraph.objects[i]=="object")if(!a||a!=RGraph.objects[i].id){RGraph.Clear(RGraph.objects[i].canvas);RGraph.objects[i].Draw()}};
RGraph.pr=function(a,b,c){var f="";c=c?c:"";switch(typeof a){case "number":if(c=="")f+="Number: ";f+=String(a);break;case "string":if(c=="")f+="String ("+a.length+"):";f+='"'+String(a)+'"';break;case "object":if(a==null){f+="null";break}f+="Object \n"+c+"(\n";for(i=0;i<a.length;++i)f+=c+"  "+i+" => "+RGraph.pr(a[i],true,c+"\t")+"\n";f=f+c+")";break;case "function":f+=a;break;case "boolean":f+="Boolean: "+(a?"true":"false");break}if(b)return f;else alert(f)};
RGraph.Registry.Set=function(a,b){return RGraph.Registry.store[a]=b};RGraph.Registry.Get=function(a){return RGraph.Registry.store[a]};
RGraph.background.Draw=function(a){var b=a.canvas,c=a.context,f=0,d=a.Get("chart.gutter"),e=a.Get("chart.variant");if(e=="3d"){c.save();c.translate(10,-5)}a.context.beginPath();c.fillStyle=a.Get("chart.background.barcolor1");f=a.canvas.height-a.Get("chart.gutter");for(var g=d;g<f;g+=80)a.context.fillRect(d,g,a.canvas.width-d*2,Math.min(40,a.canvas.height-d-g));c.fillStyle=a.Get("chart.background.barcolor2");f=a.canvas.height-d;for(g=40+d;g<f;g+=80)a.context.fillRect(d,g,a.canvas.width-d*2,g+40>a.canvas.height-
d?a.canvas.height-(d+g):40);c.stroke();if(a.Get("chart.background.grid")){c.beginPath();c.lineWidth=a.Get("chart.background.grid.width")?a.Get("chart.background.grid.width"):1;c.strokeStyle=a.Get("chart.background.grid.color");if(a.Get("chart.background.grid.hlines")){f=b.height-d;for(y=d;y<f;y+=a.Get("chart.background.grid.hsize")){c.moveTo(d,y);c.lineTo(b.width-d,y)}}if(a.Get("chart.background.grid.vlines")){f=b.width-d;for(x=d;x<=f;x+=a.Get("chart.background.grid.vsize")){c.moveTo(x,d);c.lineTo(x,
a.canvas.height-d)}}if(a.Get("chart.background.grid.border")){c.strokeStyle=a.Get("chart.background.grid.color");c.strokeRect(d,d,b.width-2*d,b.height-2*d)}}c.stroke();e=="3d"&&c.restore();if(typeof a.Get("chart.title")=="string"){if(a.type=="gantt")d/=2;RGraph.DrawTitle(b,a.Get("chart.title"),d,null,a.Get("chart.text.size")+2)}c.stroke()};
RGraph.GetDays=function(a){var b=a.getFullYear(),c=a.getDate();a=a.getMonth();if(a==0)return c;if(a>=1)c+=31;if(a>=2)c+=28;if(b>=2008&&b%4==0)c+=1;if(a>=3)c+=31;if(a>=4)c+=30;if(a>=5)c+=31;if(a>=6)c+=30;if(a>=7)c+=31;if(a>=8)c+=31;if(a>=9)c+=30;if(a>=10)c+=31;if(a>=11)c+=30;return c};
RGraph.DrawKey=function(a,b,c,f){var d=a.canvas,e=a.context;e.lineWidth=1;e.beginPath();var g=a.Get("chart.key.position"),h=a.Get("chart.text.size"),k=a.Get("chart.gutter");if(g&&g=="gutter"){f=0;b=a.Get("chart.key");d=a.type=="pie"&&a.Get("chart.align")=="left"?a.radius+a.Get("chart.gutter"):a.type=="pie"&&a.Get("chart.align")=="right"?a.canvas.width-a.radius-a.Get("chart.gutter"):d.width/2;e.font=a.Get("chart.text.size")+"pt "+a.Get("chart.text.font");for(g=0;g<b.length;++g){f+=e.measureText(b[g]).width;
f+=20;f+=10}f=d-f/2;for(g=0;g<b.length;++g){f+=10;e.fillStyle=c[g];e.fillRect(f+9,k-5-h,h,h+1);e.stroke();e.fill();e.fillStyle=a.Get("chart.text.color");RGraph.Text(e,a.Get("chart.text.font"),h,f+25,k-6-h,b[g],"top");e.fill();f+=e.measureText(b[g]).width+15}}else if(g&&g=="graph"){e.font=h+"pt "+a.Get("chart.text.font");var l=0;for(g=0;g<b.length;++g)l=Math.max(l,e.measureText(b[g]).width);l+=32;if(a.Get("chart.key.shadow")){e.shadowColor="#666";e.shadowBlur=3;e.shadowOffsetX=2;e.shadowOffsetY=2}e.beginPath();
e.fillStyle=a.Get("chart.key.background");e.strokeStyle="black";d=d.width-l-k;if(a.Get("chart.yaxispos")=="right"){d-=a.canvas.width-a.Get("chart.gutter")*2;d+=l+6}if(f!=false){if(document.all&&a.Get("chart.key.shadow")){e.beginPath();e.fillStyle="#666";e.fillRect(d+2,k+5+2,l-5,5+(h+5)*b.length);e.fill();e.fillStyle=a.Get("chart.key.background")}e.strokeRect(d,k+5,l-5,5+(h+5)*b.length);e.fillRect(d,k+5,l-5,5+(h+5)*b.length)}e.shadowColor="rgba(0,0,0,0)";for(g=b.length-1;g>=0;g--){f=Number(g)+1;e.fillStyle=
c[g];e.fillRect(d+5,5+k+5*f+h*f-h,h,h);e.fill();e.stroke();e.fillStyle=a.Get("chart.text.color");RGraph.Text(e,a.Get("chart.text.font"),h,d+21,k+5*f+h*f+4,b[g])}}else alert("[COMMON] ("+a.id+") Unknown key position: "+g)};function pd(a){RGraph.pr(a)}RGraph.array_clone=function(a){if(a==null||typeof a!="object")return a;for(var b=[],c=0;c<a.length;++c)b[c]=RGraph.array_clone(a[c]);return b};RGraph.array_reverse=function(a){for(var b=[],c=a.length-1;c>=0;c--)b.push(a[c]);return b};
RGraph.number_format=function(a,b,c){b=b?String(b):"";var f=c?String(c):"",d="",e="";RegExp.$1="";if(String(a).indexOf("e")>0)return String(b+String(a)+f);a=String(a);if(a.indexOf(".")>0){a=a.replace(/\.(.*)/,"");e=RegExp.$1}c=a.length-1;for(j=0;c>=0;j++,c--){var g=a.charAt(c);if(j%3==0&&j!=0)d+=",";d+=g}a=d;d="";for(c=a.length-1;c>=0;c--)d+=a.charAt(c);d=d.replace(/^-,/,"-");if(e.length){d=d+"."+e;RegExp.$1=""}if(d.charAt(0)=="-"){d*=-1;b="-"+b}return b+d+f};
RGraph.Contextmenu=function(a,b,c){c=RGraph.FixEventObject(c);RGraph.Registry.Get("chart.contextmenu")&&RGraph.HideContext();RGraph.HideZoomedCanvas();RGraph.HidePalette();a.__object__.Set("chart.mousedown",false);var f=c.pageX,d=c.pageY,e=document.createElement("div"),g=document.createElement("div");e.className="RGraph_contextmenu";e.__canvas__=a;e.style.position="absolute";e.style.left=0;e.style.top=0;e.style.border="1px solid black";e.style.backgroundColor="white";e.style.boxShadow="3px 3px 3px rgba(96,96,96,0.5)";
e.style.MozBoxShadow="3px 3px 3px rgba(96,96,96,0.5)";e.style.WebkitBoxShadow="3px 3px 3px rgba(96,96,96,0.5)";e.style.filter="progid:DXImageTransform.Microsoft.Shadow(color=#aaaaaa,direction=135)";e.style.opacity=0;g.className="RGraph_contextmenu_background";g.style.position="absolute";g.style.backgroundColor="#ccc";g.style.borderRight="1px solid #aaa";g.style.top=0;g.style.left=0;g.style.width="18px";g.style.height="100%";g.style.opacity=0;e=document.body.appendChild(e);g=e.appendChild(g);for(i=
0;i<b.length;++i){var h=document.createElement("div");h.__canvas__=a;h.className="RGraph_contextmenu_item";if(b[i]){h.style.padding="2px 5px 2px 23px";h.style.fontFamily="Arial";h.style.fontSize="10pt";h.style.fontWeight="normal";h.innerHTML=b[i][0];if(b[i][1])if(h.addEventListener){h.addEventListener("mouseover",function(k){k.target.style.backgroundColor="#eee";k.target.style.cursor="pointer"},false);h.addEventListener("mouseout",function(k){k.target.style.backgroundColor="white";k.target.style.cursor=
"default"},false)}else{h.attachEvent("onmouseover",function(){event.srcElement.style.backgroundColor="#eee";event.srcElement.style.cursor="hand"},false);h.attachEvent("onmouseout",function(){event.srcElement.style.backgroundColor="white";event.srcElement.style.cursor="default"},false)}else if(h.addEventListener){h.addEventListener("mouseover",function(k){k.target.style.cursor="default"},false);h.addEventListener("mouseout",function(k){k.target.style.cursor="default"},false)}else{h.attachEvent("onmouseover",
function(){event.srcElement.style.cursor="default"},false);h.attachEvent("onmouseout",function(){event.srcElement.style.cursor="default"},false)}}else{h.style.borderBottom="1px solid #ddd";h.style.marginLeft="25px"}e.appendChild(h);if(b[i]&&b[i][1])if(document.all){h.attachEvent("onclick",b[i][1]);h.attachEvent("onclick",function(){RGraph.HideContext()})}else h.addEventListener("click",b[i][1],false)}e.style.width=e.offsetWidth+"px";if(document.all)g.style.height=e.offsetHeight-10+"px";if(f+e.offsetWidth>
document.body.offsetWidth)f-=e.offsetWidth;e.style.left=f+"px";e.style.top=d+"px";setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu')) obj.style.opacity = 0.2",50);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu')) obj.style.opacity = 0.4",100);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu')) obj.style.opacity = 0.6",150);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu')) obj.style.opacity = 0.8",200);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu')) obj.style.opacity = 1",
250);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu.bg')) obj.style.opacity = 0.2",50);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu.bg')) obj.style.opacity = 0.4",100);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu.bg')) obj.style.opacity = 0.6",150);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu.bg')) obj.style.opacity = 0.8",200);setTimeout("if (obj = RGraph.Registry.Get('chart.contextmenu.bg')) obj.style.opacity = 1",250);RGraph.Registry.Set("chart.contextmenu",
e);RGraph.Registry.Set("chart.contextmenu.bg",g);RGraph.Registry.Get("chart.contextmenu").oncontextmenu=function(){return false};RGraph.Registry.Get("chart.contextmenu.bg").oncontextmenu=function(){return false};if(navigator.userAgent.indexOf("Opera")==-1)a.onclick=function(){RGraph.HideContext()};window.onclick=function(k){RGraph.HideContext();RGraph.Redraw();k.target.onclick&&k.button==0&&k.target.onclick(k)};window.onresize=function(){RGraph.HideContext()};c.stopPropagation=true;c.cancelBubble=
true;return false};RGraph.HideContext=function(){var a=RGraph.Registry.Get("chart.contextmenu"),b=RGraph.Registry.Get("chart.contextmenu.bg");if(a){a.style.visibility="hidden";a.style.display="none";RGraph.Registry.Set("chart.contextmenu",null);b.style.visibility="hidden";b.style.display="none";RGraph.Registry.Set("chart.contextmenu.bg",null)}};
RGraph.ShowContext=function(a){RGraph.HidePalette();if(a.Get("chart.contextmenu")&&a.Get("chart.contextmenu").length){var b=navigator.userAgent.indexOf("Opera")>=0,c=navigator.userAgent.indexOf("Safari")>=0,f=navigator.userAgent.indexOf("Chrome")>=0,d=navigator.userAgent.indexOf("Firefox")>0&&navigator.userAgent.indexOf("Mac")>0;if((!b&&!c||f)&&!d)a.canvas.oncontextmenu=function(e){e=RGraph.FixEventObject(e);if(e.ctrlKey)return true;RGraph.Contextmenu(a.canvas,a.Get("chart.contextmenu"),e);return false};
else a.canvas.addEventListener("dblclick",function(e){if(e.ctrlKey)return true;RGraph.Registry.Get("chart.contextmenu")||RGraph.Contextmenu(a.canvas,a.Get("chart.contextmenu"),e)},false)}};
RGraph.DrawBars=function(a){var b=a.Get("chart.background.hbars");a.context.beginPath();for(i=0;i<b.length;++i){if(b[i][1]==null)b[i][1]=a.max;else if(b[i][0]+b[i][1]>a.max)b[i][1]=a.max-b[i][0];if(Math.abs(b[i][1])>a.max)b[i][1]=-1*a.max;if(Math.abs(b[i][0])>a.max)b[i][0]=a.max;if(b[i][0]+b[i][1]<-1*a.max)b[i][1]=-1*(a.max+b[i][0]);var c=a.grapharea-b[i][0]/a.max*a.grapharea,f=Math.min(b[i][1],a.max-b[i][0])/a.max*a.grapharea;if(a.Get("chart.xaxispos")=="center"){c/=2;f/=2}c+=a.Get("chart.gutter");
var d=a.Get("chart.gutter");c=c-f;var e=a.canvas.width-2*a.Get("chart.gutter");f=f;if(navigator.userAgent.indexOf("Opera")!=-1&&a.Get("chart.xaxispos")=="center"&&f<0){f*=-1;c-=f}a.context.fillStyle=b[i][2];a.context.fillRect(d,c,e,f)}a.context.fill()};
RGraph.DrawInGraphLabels=function(a){var b=a.context,c=a.Get("chart.labels.ingraph");RGraph.NoShadow(a);if(c&&c.length>0)for(var f=0;f<c.length;++f)if(c[f]){var d=a.coords[f];if(d&&d.length>0){var e=a.type=="bar"?d[0]+d[2]/2:d[0];d=(a.type=="bar"?d[1]+d[3]/2:d[1])-5;b.beginPath();b.fillStyle="black";b.strokeStyle="#666";if(a.type=="bar"){if(a.Get("chart.variant")=="dot")b.moveTo(e,d-15);else if(a.Get("chart.variant")=="arrow")b.moveTo(e,d-15);else{b.arc(e,d,1,0,6.28,0);b.moveTo(e,d)}b.lineTo(e,d-
25)}else if(a.type=="line"){b.moveTo(e,d-5);b.lineTo(e,d-25);b.moveTo(e,d);b.lineTo(e-3,d-7);b.lineTo(e+3,d-7);b.closePath()}b.stroke();b.fill();b.measureText(c[f]);RGraph.Text(b,"Verdana",a.Get("chart.text.size"),e,d-25,String(c[f]),"bottom","center",null,null,"#fff");b.fill()}}};
RGraph.FixEventObject=function(a){if(document.all){a=event;a.pageX=event.clientX+document.body.scrollLeft;a.pageY=event.clientY+document.body.scrollTop;a.target=event.srcElement;if(!document.body.scrollTop&&document.documentElement.scrollTop){a.pageX+=parseInt(document.documentElement.scrollLeft);a.pageY+=parseInt(document.documentElement.scrollTop)}}if(typeof a.offsetX=="undefined"&&typeof a.offsetY=="undefined"){var b=RGraph.getMouseXY(a);a.offsetX=b[0];a.offsetY=b[1]}return a};
RGraph.DrawCrosshairs=function(a){if(a.Get("chart.crosshairs")){var b=a.canvas;if(a.Get("chart.tooltips")&&a.Get("chart.tooltips").length>0){alert("["+a.type.toUpperCase()+"] Sorry - you cannot have crosshairs enabled with tooltips! Turning off crosshairs...");a.Set("chart.crosshairs",false)}else b.onmousemove=function(c){c=RGraph.FixEventObject(c);var f=a.canvas,d=a.context,e=a.Get("chart.gutter"),g=f.width,h=f.height,k=RGraph.getMouseXY(c);c=k[0];k=k[1];RGraph.Clear(f);a.Draw();if(c>e&&k>e&&c<g-
e&&k<h-e){d.lineWidth=1;d.beginPath();d.strokeStyle=a.Get("chart.crosshairs.color");d.moveTo(c,e);d.lineTo(c,h-e);d.moveTo(e,k);d.lineTo(g-e,k);d.stroke()}}}};
RGraph.Annotate=function(a,b){if(a.Get("chart.annotatable")){var c=a.canvas,f=a.context;c.onmousedown=function(d){if(d.button==0){d.target.__object__.Set("chart.mousedown",true);var e=d.target.__object__.canvas.getContext("2d");e.beginPath();var g=RGraph.getMouseXY(d);d=g[0];g=g[1];RGraph.Registry.Set("annotate.actions",[a.Get("chart.annotate.color")]);e.strokeStyle=a.Get("chart.annotate.color");e.moveTo(d,g);e.lineWidth=1;RGraph.Registry.Set("started.annotating",false)}return false};window.onmouseup=
function(d){for(var e=document.getElementsByTagName("canvas"),g=0;g<e.length;++g)e[g].__object__&&e[g].__object__.Set("chart.mousedown",false);if(RGraph.Registry.Get("annotate.actions")&&RGraph.Registry.Get("annotate.actions").length>0&&window.localStorage){d="__rgraph_annotations_"+d.target.id+"__";e=window.localStorage[d]?window.localStorage[d]+"|":"";e+=RGraph.Registry.Get("annotate.actions");window.localStorage[d]=e}RGraph.Registry.Set("annotate.actions",[])};c.onmouseup=window.onmouseup;c.onmouseout=
window.onmouseup;c.onmousemove=function(d){d=RGraph.FixEventObject(d);var e=d.target.__object__,g=RGraph.getMouseXY(d);d=g[0];g=g[1];var h=e.Get("chart.gutter"),k=c.width,l=c.height;e.context.lineWidth=1;if(d>h&&d<k-h&&g>h&&g<l-h){c.style.cursor="crosshair";if(e.Get("chart.mousedown"))if(d>h&&d<k-h&&g>h&&g<l-h){if(e.type!="hbar"&&e.type!="gantt"||d>3*h){if(RGraph.Registry.Get("started.annotating")==false){f.moveTo(d,g);RGraph.Registry.Set("started.annotating",true)}f.lineTo(d,g);RGraph.Registry.Set("annotate.actions",
RGraph.Registry.Get("annotate.actions")+"|"+d+","+g);f.stroke()}}else f.moveTo(d,g)}else c.style.cursor="default"};b||RGraph.ReplayAnnotations(a)}};
RGraph.Showpalette=function(a){var b=navigator.userAgent.indexOf("Safari")?true:false;a=RGraph.FixEventObject(a);var c=a.target.parentNode.__canvas__;c.getContext("2d");var f=c.__object__;c=document.createElement("DIV");RGraph.getMouseXY(a);c.__object__=f;c.className="RGraph_palette";c.style.position="absolute";c.style.backgroundColor="white";c.style.border="1px solid black";c.style.left=0;c.style.top=0;c.style.padding="3px";c.style.paddingBottom=0;c.style.paddingRight=0;c.style.opacity=0;c.style.boxShadow=
"rgba(96,96,96,0.5) 3px 3px 3px";c.style.WebkitBoxShadow="rgba(96,96,96,0.5) 3px 3px 3px";c.style.MozBoxShadow="rgba(96,96,96,0.5) 3px 3px 3px";c.style.filter="progid:DXImageTransform.Microsoft.Shadow(color=#666666,direction=135)";b="padding: 1px; display: inline; display: inline; display: inline-block; width: 15px; height: 15px; margin-right: 3px; cursor: "+(document.all?"hand;":"pointer; ")+(b?"margin-bottom: 3px":"");f="";var d=["red","blue","green","black","yellow","magenta","pink","cyan","purple",
"#ddf","gray","#36905c"];for(i=0;i<d.length;++i){f=f+'<span  onmouseover="this.style.border = \'1px black solid\'; this.style.padding = 0" onmouseout="this.style.border = 0; this.style.padding = \'1px\'"  style="background-color: '+d[i]+"; "+b+"\" onclick=\"this.parentNode.__object__.Set('chart.annotate.color', this.style.backgroundColor); this.parentNode.style.display = 'none'\">&nbsp;</span>";if(i==5)f+="<br />"}c.innerHTML=f;document.body.appendChild(c);c.style.width=c.offsetWidth-5+"px";c.style.height=
c.offsetHeight-5+"px";c.style.left=Math.max(0,a.pageX-c.offsetWidth-2)+"px";c.style.top=a.pageY-c.offsetHeight-2+"px";RGraph.Registry.Set("palette",c);setTimeout("RGraph.Registry.Get('palette').style.opacity = 0.2",50);setTimeout("RGraph.Registry.Get('palette').style.opacity = 0.4",100);setTimeout("RGraph.Registry.Get('palette').style.opacity = 0.6",150);setTimeout("RGraph.Registry.Get('palette').style.opacity = 0.8",200);setTimeout("RGraph.Registry.Get('palette').style.opacity = 1",250);RGraph.HideContext();
window.onclick=function(){RGraph.HidePalette()};a.cancelBubble=true;a.stopPropagation=true};RGraph.HidePalette=function(){var a=RGraph.Registry.Get("palette");if(typeof a=="object"&&a){a.style.visibility="hidden";a.style.display="none";RGraph.Registry.Set("palette",null)}};RGraph.ClearAnnotations=function(a){if(window.localStorage&&window.localStorage["__rgraph_annotations_"+a+"__"]&&window.localStorage["__rgraph_annotations_"+a+"__"].length)window.localStorage["__rgraph_annotations_"+a+"__"]=[]};
RGraph.ReplayAnnotations=function(a){if(window.localStorage){var b=a.context;a=window.localStorage["__rgraph_annotations_"+a.id+"__"];var c,f,d,e;b.lineWidth=2;if(a&&a.length){a=a.split("|");c=0;for(f=a.length;c<f;++c)if(a[c].match(/^[0-9]+,[0-9]+$/)){e=a[c].split(",");if(d){b.moveTo(e[0],e[1]);d=false}else b.lineTo(e[0],e[1])}else{b.stroke();b.beginPath();b.strokeStyle=a[c];d=true}b.stroke()}}};RGraph.rtrim=function(a){return a.replace(/( |\n|\r|\t)+$/,"")};
RGraph.Draw3DAxes=function(a){var b=a.Get("chart.gutter"),c=a.context;a=a.canvas;c.strokeStyle="#aaa";c.fillStyle="#ddd";c.beginPath();c.moveTo(b,b);c.lineTo(b+10,b-5);c.lineTo(b+10,a.height-b-5);c.lineTo(b,a.height-b);c.closePath();c.stroke();c.fill();c.beginPath();c.moveTo(b,a.height-b);c.lineTo(b+10,a.height-b-5);c.lineTo(a.width-b+10,a.height-b-5);c.lineTo(a.width-b,a.height-b);c.closePath();c.stroke();c.fill()};
RGraph.NoShadow=function(a){a.context.shadowColor="rgba(0,0,0,0)";a.context.shadowBlur=0;a.context.shadowOffsetX=0;a.context.shadowOffsetY=0};
RGraph.Zoom=function(a){a=RGraph.FixEventObject(a);if(a.target.parentNode.__canvas__.__object__.Get("chart.zoom.mode")=="window")return RGraph.ZoomWindow(a);a=a.target.__canvas__;a.getContext("2d");var b=a.__object__,c=RGraph.getCanvasXY(a),f=b.Get("chart.zoom.factor")-1,d=c[0];c=c[1];var e=document.createElement("img");e.className="RGraph_zoomed_canvas";e.style.border="3px solid gray";e.style.width=a.width+"px";e.style.height=a.height+"px";e.style.position="absolute";e.style.left=d+"px";e.style.top=
c+"px";e.style.backgroundColor="white";e.style.opacity=b.Get("chart.zoom.fade.in")?0:1;e.style.zIndex=99;e.src=a.toDataURL();document.body.appendChild(e);__zoomedimage__=e;__zoomedimage__.obj=b;e.onclick=function(o){o.cancelBubble=true;document.all&&event.stopPropagation();return false};setTimeout(function(){window.onclick=RGraph.HideZoomedCanvas},1);var g=parseInt(a.width),h=parseInt(a.height);e=b.Get("chart.zoom.frames");var k=b.Get("chart.zoom.delay");if(b.Get("chart.zoom.hdir")=="center")for(var l=
1;l<=e;++l){var n=g*f*(l/e)+g,m=d+a.width;m=d+a.width/2-n/2;setTimeout("__zoomedimage__.style.width = '"+String(n)+"px'; __zoomedimage__.style.left = '"+m+"px'",l*k)}else if(b.Get("chart.zoom.hdir")=="left")for(l=1;l<=e;++l){n=g*f*(l/e)+g;m=d+a.width;setTimeout("__zoomedimage__.style.width = '"+String(n)+"px'; __zoomedimage__.style.left = '"+(m-n)+"px'",l*k)}else for(l=1;l<=e;++l)setTimeout("__zoomedimage__.style.width = '"+String(g*f*(l/e)+g)+"px'",l*k);if(b.Get("chart.zoom.vdir")=="up")for(l=1;l<=
e;++l){d=h*f*(l/e)+h;g=c+a.height;setTimeout("__zoomedimage__.style.height = '"+String(d)+"px'; __zoomedimage__.style.top = '"+(g-d)+"px'",l*k)}else if(b.Get("chart.zoom.vdir")=="center")for(l=1;l<=e;++l){d=h*f*(l/e)+h;g=c+a.height/2+d/2;setTimeout("__zoomedimage__.style.height = '"+String(d)+"px'; __zoomedimage__.style.top = '"+(g-d)+"px'",l*k)}else for(l=1;l<=e;++l)setTimeout("__zoomedimage__.style.height = '"+String(h*f*(l/e)+h)+"px'",l*k);if(b.Get("chart.zoom.fade.in"))for(l=1;l<=e;++l)setTimeout("__zoomedimage__.style.opacity = "+
String(l/e),l*k);if(b.Get("chart.zoom.shadow"))for(l=1;l<=e;++l){setTimeout("__zoomedimage__.style.boxShadow = 'rgba(128,128,128,"+Number(l/e)/2+") 0 0 15px'",l*k);setTimeout("__zoomedimage__.style.MozBoxShadow = 'rgba(128,128,128,"+Number(l/e)/2+") 0 0 15px'",l*k);setTimeout("__zoomedimage__.style.WebkitBoxShadow = 'rgba(128,128,128,"+Number(l/e)/2+") 0 0 15px'",l*k)}if(b.Get("chart.zoom.background")){a=document.createElement("DIV");a.style.backgroundColor="#999";a.style.opacity=0;a.style.position=
"absolute";a.style.top=0;a.style.left=0;a.style.width=RGraph.getPageWidth()+"px";a.style.height=RGraph.getPageHeight()+"px";a.style.zIndex=98;a.oncontextmenu=function(o){return RGraph.HideZoomedCanvas(o)};for(l=1;l<=e;++l)setTimeout("__zoomedbackground__.style.opacity = "+Number(0.04*l),l*k);a.origHeight=a.style.height;document.body.appendChild(a);__zoomedbackground__=a;window.onresize=RGraph.HideZoomedCanvas;for(l=1;l<=e;++l)setTimeout("__zoomedbackground__.style.opacity = "+Number(l/e)*0.5,l*k)}};
RGraph.ZoomWindow=function(a){a.onmousemove=function(b){b=RGraph.FixEventObject(b);var c=b.target.__object__,f=RGraph.getMouseXY(b);if(RGraph.Registry.Get("chart.zoomed.div")){d=RGraph.Registry.Get("chart.zoomed.div");e=RGraph.Registry.Get("chart.zoomed.img")}else{var d=document.createElement("div");d.className="RGraph_zoom_window";d.style.width=c.Get("chart.zoom.thumbnail.width")+"px";d.style.height=c.Get("chart.zoom.thumbnail.height")+"px";d.style.border="2px dashed gray";d.style.position="absolute";
d.style.overflow="hidden";d.style.backgroundColor="white";d.style.left="-1000px";d.style.top="-1000px";d.style.borderRadius="5px";d.style.MozBorderRadius="5px";d.style.WebkitBorderRadius="5px";if(c.Get("chart.zoom.shadow")){d.style.boxShadow="rgba(0,0,0,0.5) 3px 3px 3px";d.style.MozBoxShadow="rgba(0,0,0,0.5) 3px 3px 3px";d.style.WebkitBoxShadow="rgba(0,0,0,0.5) 3px 3px 3px"}d.__object__=c;document.body.appendChild(d);var e=document.createElement("img");e.width=c.canvas.width*c.Get("chart.zoom.factor");
e.height=c.canvas.height*c.Get("chart.zoom.factor");e.style.position="relative";e.style.backgroundColor="white";e.src=c.canvas.toDataURL();d.appendChild(e);RGraph.Registry.Set("chart.zoomed.div",d);RGraph.Registry.Set("chart.zoomed.img",e);setTimeout("RGraph.Registry.Get('chart.zoomed.div').__object__.canvas.onmouseover()",5)}d&&d.style.opacity<1&&setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 1",400);RGraph.getCanvasXY(c.canvas);d.style.left=b.pageX-c.Get("chart.zoom.thumbnail.width")-
7+"px";d.style.top=b.pageY-c.Get("chart.zoom.thumbnail.height")-7+"px";b=c.Get("chart.zoom.thumbnail.width")/2-f[0]*c.Get("chart.zoom.factor");f=c.Get("chart.zoom.thumbnail.height")/2-f[1]*c.Get("chart.zoom.factor");e.style.left=b+c.Get("chart.zoom.thumbnail.width")/2*c.Get("chart.zoom.factor")+"px";e.style.top=f+c.Get("chart.zoom.thumbnail.height")/2*c.Get("chart.zoom.factor")+"px"};a.onmouseover=function(){var b=RGraph.Registry.Get("chart.zoomed.div");if(b){var c=b.__object__,f=c.Get("chart.zoom.thumbnail.width"),
d=c.Get("chart.zoom.thumbnail.height");b.style.width=0;b.style.height=0;if(c.Get("chart.zoom.fade.in")){RGraph.Registry.Get("chart.zoomed.div").style.opacity=0.2;setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.4",100);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.6",200);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.8",300);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 1",400)}else setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 1",
1);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.width = '"+f*0.2+"px'",75);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.width = '"+f*0.4+"px'",150);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.width = '"+f*0.6+"px'",225);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.width = '"+f*0.8+"px'",300);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.width = '"+f*1+"px'",325);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.height = '"+d*
0.2+"px'",75);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.height = '"+d*0.4+"px'",150);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.height = '"+d*0.6+"px'",225);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.height = '"+d*0.8+"px'",300);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.height = '"+d*1+"px'",375)}};a.onmouseout=function(){if(RGraph.Registry.Get("chart.zoomed.div").__object__.Get("chart.zoom.fade.out")){RGraph.Registry.Get("chart.zoomed.div").style.opacity=
0.8;setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.6",100);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.4",200);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0.2",300);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.opacity = 0",400);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.left = '-400px'",400);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.top = '-400px'",400)}else{setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.left = '-400px'",
1);setTimeout("RGraph.Registry.Get('chart.zoomed.div').style.top = '-400px'",1)}}};RGraph.ShowZoomWindow=function(a){a.Get("chart.gutter");a.Get("chart.zoom.mode")=="thumbnail"&&RGraph.ZoomWindow(a.canvas)};
RGraph.OldBrowserCompat=function(a){if(!a.measureText)a.measureText=function(b){var c=document.createElement("DIV");c.innerHTML=b;c.style.backgroundColor="white";c.style.position="absolute";c.style.top=-100;c.style.left=0;document.body.appendChild(c);b={width:c.offsetWidth};c.style.display="none";return b};if(!a.fillText)a.fillText=function(){return false}};
RGraph.getSegment=function(a){RGraph.FixEventObject(a);var b=a.target.__object__,c=RGraph.getMouseXY(a),f=c[0]-b.centerx,d=c[1]-b.centery,e=b.radius;a=Math.atan(d/f);var g=d/Math.sin(a),h=b.angles,k=[];a*=57.3;if(b.type=="radar"||b.type=="donut")if(isNaN(g)&&Math.abs(c[0])<b.centerx-e||isNaN(g)&&Math.abs(c[0])>b.centerx+e||!isNaN(g)&&Math.abs(g)>e)return;else if(b.Get("chart.isdonut")&&Math.abs(g)<b.radius/2)return;if(f<0&&d>=0)a+=180;else if(f<0&&d<0)a+=180;else if(f>0&&d<0)a+=360;for(c=0;c<h.length;++c)if(a>=
h[c][0]&&a<h[c][1]){g=Math.abs(g);if(b.type=="radar"&&g>h[c][2])return null;if(b.type=="pie"&&g>b.radius)return null;if(b.type=="donut"&&(g>b.radius||g<b.holewidth))return null;k[0]=b.centerx;k[1]=b.centery;k[2]=b.type=="radar"?h[c][2]:b.radius;k[3]=h[c][0];k[4]=h[c][1];return k}return null};RGraph.Async=function(a,b){return setTimeout(a,b?b:1)};RGraph.random=function(a,b,c){return Number(((b-a)*Math.random()+a).toFixed(c?c:0))};
RGraph.strokedCurvyRect=function(a,b,c,f,d,e,g,h,k,l){e=e?e:3;g=g||g==null?true:false;h=h||h==null?true:false;k=k||k==null?true:false;l=l||l==null?true:false;a.beginPath();a.moveTo(b+(g?e:0),c);a.lineTo(b+f-(h?e:0),c);h&&a.arc(b+f-e,c+e,e,Math.PI*1.5,Math.PI*2,false);a.lineTo(b+f,c+d-(k?e:0));k&&a.arc(b+f-e,c-e+d,e,Math.PI*2,Math.PI*0.5,false);a.lineTo(b+(l?e:0),c+d);l&&a.arc(b+e,c-e+d,e,Math.PI*0.5,Math.PI,false);a.lineTo(b,c+(g?e:0));g&&a.arc(b+e,c+e,e,Math.PI,Math.PI*1.5,false);a.stroke()};
RGraph.filledCurvyRect=function(a,b,c,f,d,e,g,h,k,l){e=e?e:3;g=g||g==null?true:false;h=h||h==null?true:false;k=k||k==null?true:false;l=l||l==null?true:false;a.beginPath();if(g){a.moveTo(b+e,c+e);a.arc(b+e,c+e,e,Math.PI,1.5*Math.PI,false)}else a.fillRect(b,c,e,e);if(h){a.moveTo(b+f-e,c+e);a.arc(b+f-e,c+e,e,1.5*Math.PI,0,false)}else{a.moveTo(b+f-e,c);a.fillRect(b+f-e,c,e,e)}if(k){a.moveTo(b+f-e,c+d-e);a.arc(b+f-e,c-e+d,e,0,Math.PI/2,false)}else{a.moveTo(b+f-e,c+d-e);a.fillRect(b+f-e,c+d-e,e,e)}if(l){a.moveTo(b+
e,c+d-e);a.arc(b+e,c-e+d,e,Math.PI/2,Math.PI,false)}else{a.moveTo(b,c+d-e);a.fillRect(b,c+d-e,e,e)}a.fillRect(b+e,c,f-e-e,d);a.fillRect(b,c+e,f,d-e-e);a.fill()};RGraph.Timer=function(a){var b=new Date;console.log(a+": "+b.getSeconds()+"."+b.getMilliseconds())};
RGraph.HideZoomedCanvas=function(){if(typeof __zoomedimage__=="object"){obj=__zoomedimage__.obj;if(obj.Get("chart.zoom.fade.out")){for(var a=10,b=1;a>=0;--a,++b)typeof __zoomedimage__=="object"&&setTimeout("__zoomedimage__.style.opacity = "+String(a/10),b*30);typeof __zoomedbackground__=="object"&&setTimeout("__zoomedbackground__.style.opacity = "+String(a/10),b*30)}if(typeof __zoomedimage__=="object")setTimeout("__zoomedimage__.style.display = 'none'",obj.Get("chart.zoom.fade.out")?310:0);if(typeof __zoomedbackground__==
"object")setTimeout("__zoomedbackground__.style.display = 'none'",obj.Get("chart.zoom.fade.out")?310:0)}};RGraph.getPageWidth=function(){return document.body.clientWidth+16};
RGraph.getPageHeight=function(){if(navigator.userAgent.indexOf("Chrome")!=-1)return Math.max(document.body.clientHeight,document.body.scrollHeight);else if(navigator.userAgent.indexOf("Safari")!=-1)return Math.max(document.body.clientHeight,document.body.scrollHeight)+40;else if(navigator.userAgent.indexOf("Opera")!=-1){var a=Math.max(document.body.clientHeight,document.body.offsetHeight);return a=Math.max(a,document.body.scrollHeight)+40}else return navigator.userAgent.indexOf("MSIE")!=-1?Math.max(document.body.scrollHeight,
document.body.clientHeight)+40:Math.max(window.innerHeight,Math.max(document.body.clientHeight,document.body.scrollHeight))+40};if(typeof RGraph=="undefined")RGraph={};
RGraph.Line=function(a){this.id=a;this.canvas=document.getElementById(a);this.context=this.canvas.getContext?this.canvas.getContext("2d"):null;this.canvas.__object__=this;this.type="line";this.max=0;this.coords=[];this.hasnegativevalues=false;RGraph.OldBrowserCompat(this.context);this.properties={"chart.background.barcolor1":"rgba(0,0,0,0)","chart.background.barcolor2":"rgba(0,0,0,0)","chart.background.grid":1,"chart.background.grid.width":1,"chart.background.grid.hsize":25,"chart.background.grid.vsize":25,
"chart.background.grid.color":"#ddd","chart.background.grid.vlines":true,"chart.background.grid.hlines":true,"chart.background.grid.border":true,"chart.background.hbars":null,"chart.labels":null,"chart.labels.ingraph":null,"chart.xtickgap":20,"chart.smallxticks":3,"chart.largexticks":5,"chart.ytickgap":20,"chart.smallyticks":3,"chart.largeyticks":5,"chart.linewidth":1,"chart.colors":["red","#0f0","#00f","#f0f","#ff0","#0ff"],"chart.hmargin":0,"chart.tickmarks.dot.color":"white","chart.tickmarks":null,
"chart.ticksize":3,"chart.gutter":25,"chart.tickdirection":-1,"chart.yaxispoints":5,"chart.fillstyle":null,"chart.xaxispos":"bottom","chart.yaxispos":"left","chart.xticks":null,"chart.text.size":10,"chart.text.angle":0,"chart.text.color":"black","chart.text.font":"Verdana","chart.ymin":null,"chart.ymax":null,"chart.title":"","chart.title.vpos":null,"chart.shadow":false,"chart.shadow.offsetx":2,"chart.shadow.offsety":2,"chart.shadow.blur":3,"chart.shadow.color":"rgba(0,0,0,0.5)","chart.tooltips":null,
"chart.tooltip.effect":"fade","chart.stepped":false,"chart.key":[],"chart.key.background":"white","chart.key.position":"graph","chart.key.shadow":false,"chart.contextmenu":null,"chart.ylabels":true,"chart.ylabels.count":5,"chart.noaxes":false,"chart.noxaxis":false,"chart.noendxtick":false,"chart.units.post":"","chart.units.pre":"","chart.scale.decimals":0,"chart.crosshairs":false,"chart.crosshairs.color":"#333","chart.annotatable":false,"chart.annotate.color":"black","chart.axesontop":false,"chart.filled.range":false,
"chart.variant":null,"chart.axis.color":"black","chart.zoom.factor":1.5,"chart.zoom.fade.in":true,"chart.zoom.fade.out":true,"chart.zoom.hdir":"right","chart.zoom.vdir":"down","chart.zoom.frames":15,"chart.zoom.delay":33,"chart.zoom.shadow":true,"chart.zoom.mode":"canvas","chart.zoom.thumbnail.width":75,"chart.zoom.thumbnail.height":75,"chart.zoom.background":true};for(var b=1;b<arguments.length;++b)if(typeof arguments[b]=="null"||!arguments[b])arguments[b]=[];typeof RGraph=="undefined"&&alert("[LINE] Fatal error: The common library does not appear to have been included");
this.original_data=[];for(b=1;b<arguments.length;++b)this.original_data[b-1]=RGraph.array_clone(arguments[b]);this.canvas||alert("[LINE] Fatal error: no canvas support")};RGraph.Line.prototype.Set=function(a,b){if(a=="chart.tooltips"){this.properties["chart.tooltips"]=[];for(var c=1;c<arguments.length;c++)for(j=0;j<arguments[c].length;j++)this.Get("chart.tooltips").push(arguments[c][j])}this.properties[a]=b};RGraph.Line.prototype.Get=function(a){return this.properties[a]};
RGraph.Line.prototype.Draw=function(){this.gutter=this.Get("chart.gutter");this.data=RGraph.array_clone(this.original_data);this.max=0;this.data=RGraph.array_reverse(this.data);if(this.Get("chart.filled")&&!this.Get("chart.filled.range")&&this.data.length>1)for(var a=[],b=0;b<this.data.length;++b)for(var c=0;c<this.data[b].length;++c){this.data[b][c]=Number(a[c]?a[c]:0)+this.data[b][c];a[c]=this.data[b][c]}if(this.Get("chart.ymax")){this.max=this.Get("chart.ymax");this.min=this.Get("chart.ymin")?
this.Get("chart.ymin"):0;this.scale=[((this.max-this.min)*0.2+this.min).toFixed(this.Get("chart.scale.decimals")),((this.max-this.min)*0.4+this.min).toFixed(this.Get("chart.scale.decimals")),((this.max-this.min)*0.6+this.min).toFixed(this.Get("chart.scale.decimals")),((this.max-this.min)*0.8+this.min).toFixed(this.Get("chart.scale.decimals")),this.max.toFixed(this.Get("chart.scale.decimals"))]}else{this.min=this.Get("chart.ymin")?this.Get("chart.ymin"):0;for(dataset=0;dataset<this.data.length;++dataset)for(a=
0;a<this.data[dataset].length;a++){this.max=Math.max(this.max,this.data[dataset][a]?Math.abs(parseFloat(this.data[dataset][a])):0);this.hasnegativevalues=this.data[dataset][a]<0}this.scale=RGraph.getScale(Math.abs(parseFloat(this.max)));this.max=this.scale[4]?this.scale[4]:0;if(this.Get("chart.ymin")){this.scale[0]=(this.max-this.Get("chart.ymin"))*0.2+this.Get("chart.ymin");this.scale[1]=(this.max-this.Get("chart.ymin"))*0.4+this.Get("chart.ymin");this.scale[2]=(this.max-this.Get("chart.ymin"))*
0.6+this.Get("chart.ymin");this.scale[3]=(this.max-this.Get("chart.ymin"))*0.8+this.Get("chart.ymin");this.scale[4]=(this.max-this.Get("chart.ymin"))*1+this.Get("chart.ymin")}if(this.Get("chart.scale.decimals")){this.scale[0]=Number(this.scale[0]).toFixed(this.Get("chart.scale.decimals"));this.scale[1]=Number(this.scale[1]).toFixed(this.Get("chart.scale.decimals"));this.scale[2]=Number(this.scale[2]).toFixed(this.Get("chart.scale.decimals"));this.scale[3]=Number(this.scale[3]).toFixed(this.Get("chart.scale.decimals"));
this.scale[4]=Number(this.scale[4]).toFixed(this.Get("chart.scale.decimals"))}}RGraph.ShowContext(this);this.coords=[];this.grapharea=this.canvas.height-2*this.gutter;this.halfgrapharea=this.grapharea/2;this.halfTextHeight=this.Get("chart.text.size")/2;this.Get("chart.xaxispos")=="bottom"&&this.hasnegativevalues&&alert("[LINE] You have negative values and the X axis is at the bottom. This is not good...");this.Get("chart.variant")=="3d"&&RGraph.Draw3DAxes(this);RGraph.background.Draw(this);this.Get("chart.background.hbars")&&
this.Get("chart.background.hbars").length>0&&RGraph.DrawBars(this);this.Get("chart.axesontop")==false&&this.DrawAxes();a=this.data.length-1;for(b=0;a>=0;a--,b++){this.context.beginPath();if(this.Get("chart.shadow")&&!this.Get("chart.filled")){this.context.shadowColor=this.Get("chart.shadow.color");this.context.shadowBlur=this.Get("chart.shadow.blur");this.context.shadowOffsetX=this.Get("chart.shadow.offsetx");this.context.shadowOffsetY=this.Get("chart.shadow.offsety")}else this.Get("chart.filled")&&
this.Get("chart.shadow")&&alert("[LINE] Shadows are not permitted when the line is filled");if(this.Get("chart.fillstyle"))if(typeof this.Get("chart.fillstyle")=="object"&&this.Get("chart.fillstyle")[b])var f=this.Get("chart.fillstyle")[b];else if(typeof this.Get("chart.fillstyle")=="string")f=this.Get("chart.fillstyle");else alert("[LINE] Warning: chart.fillstyle must be either a string or an array with the same number of elements as you have sets of data");else f=this.Get("chart.filled")?this.Get("chart.colors")[b]:
null;this.DrawLine(this.data[a],this.Get("chart.colors")[b],f);this.context.stroke()}this.Get("chart.axesontop")&&this.DrawAxes();this.DrawLabels();this.DrawRange();this.Get("chart.key").length&&RGraph.DrawKey(this,this.Get("chart.key"),this.Get("chart.colors"));RGraph.DrawInGraphLabels(this);RGraph.DrawCrosshairs(this);RGraph.Annotate(this);if(this.Get("chart.filled")&&this.Get("chart.filled.range")&&this.data.length==2){this.context.beginPath();f=this.coords.length/2;this.context.lineWidth=this.Get("chart.linewidth");
this.context.strokeStyle=this.Get("chart.colors")[0];for(a=0;a<f;++a)a==0?this.context.moveTo(this.coords[a][0],this.coords[a][1]):this.context.lineTo(this.coords[a][0],this.coords[a][1]);this.context.stroke();this.context.beginPath();if(this.Get("chart.colors")[1])this.context.strokeStyle=this.Get("chart.colors")[1];for(a=this.coords.length-1;a>=f;--a)a==this.coords.length-1?this.context.moveTo(this.coords[a][0],this.coords[a][1]):this.context.lineTo(this.coords[a][0],this.coords[a][1]);this.context.stroke()}else this.Get("chart.filled")&&
this.Get("chart.filled.range")&&alert("[LINE] You must have only two sets of data for a filled range chart");RGraph.ShowZoomWindow(this)};
RGraph.Line.prototype.DrawAxes=function(){var a=this.gutter;if(!this.Get("chart.noaxes")){RGraph.NoShadow(this);this.context.lineWidth=1;this.context.strokeStyle=this.Get("chart.axis.color");this.context.beginPath();if(this.Get("chart.noxaxis")==false)if(this.Get("chart.xaxispos")=="center"){this.context.moveTo(a,this.grapharea/2+a);this.context.lineTo(this.canvas.width-a,this.grapharea/2+a)}else{this.context.moveTo(a,this.canvas.height-a);this.context.lineTo(this.canvas.width-a,this.canvas.height-
a)}if(this.Get("chart.yaxispos")=="left"){this.context.moveTo(a,a);this.context.lineTo(a,this.canvas.height-a)}else{this.context.moveTo(this.canvas.width-a,a);this.context.lineTo(this.canvas.width-a,this.canvas.height-a)}if(this.Get("chart.noxaxis")==false){var b=(this.canvas.width-2*a)/(this.Get("chart.xticks")?this.Get("chart.xticks"):this.data[0].length);for(x=a+(this.Get("chart.yaxispos")=="left"?b:0);x<=this.canvas.width-a+1;x+=b){if(this.Get("chart.yaxispos")=="right"&&x>=this.canvas.width-
a-1)break;if(this.Get("chart.noendxtick"))if(this.Get("chart.yaxispos")=="left"&&x>=this.canvas.width-a)break;else if(this.Get("chart.yaxispos")=="right"&&x==a)continue;var c=this.Get("chart.xaxispos")=="center"?this.canvas.height/2-3:this.canvas.height-a,f=this.Get("chart.xaxispos")=="center"?c+6:this.canvas.height-a-(x%60==0?this.Get("chart.largexticks")*this.Get("chart.tickdirection"):this.Get("chart.smallxticks")*this.Get("chart.tickdirection"));this.context.moveTo(x,c);this.context.lineTo(x,
f)}}f=c=0;if(this.Get("chart.yaxispos")=="right")f=this.canvas.width-2*a;if(this.Get("chart.xaxispos")=="center"){c=this.grapharea/10;b=this.Get("chart.yaxispos")=="left"?a:this.canvas.width-a+this.Get("chart.smallyticks");for(y=a;y<this.grapharea/2+a;y+=c){this.context.moveTo(this.Get("chart.yaxispos")=="left"?a-this.Get("chart.smallyticks"):this.canvas.width-a,y);this.context.lineTo(b,y)}for(y=a+this.halfgrapharea+c;y<=this.grapharea+a;y+=c){this.context.moveTo(this.Get("chart.yaxispos")=="left"?
a-this.Get("chart.smallyticks"):this.canvas.width-a,y);this.context.lineTo(b,y)}}else{b=this.Get("chart.yaxispos")=="left"?a-this.Get("chart.smallyticks"):this.canvas.width-a+this.Get("chart.smallyticks");for(y=a;y<this.canvas.height-a&&c<10;y+=(this.canvas.height-2*a)/10){this.context.moveTo(a+f,y);this.context.lineTo(b,y);c+=1}}this.context.stroke()}};
RGraph.Line.prototype.DrawLabels=function(){this.context.fillStyle=this.Get("chart.text.color");this.context.lineWidth=1;RGraph.NoShadow(this);if(this.Get("chart.ylabels")){var a=this.Get("chart.gutter"),b=this.Get("chart.text.size"),c=this.Get("chart.units.pre"),f=this.Get("chart.units.post"),d=this.context,e=this.Get("chart.yaxispos")=="left"?a-5:this.canvas.width-a+5,g=this.Get("chart.yaxispos")=="left"?"right":"left",h=this.Get("chart.text.font"),k=this.Get("chart.ylabels.count");if(this.Get("chart.xaxispos")==
"center"){var l=this.grapharea/2;RGraph.Text(d,h,b,e,a+0*l+this.halfTextHeight,RGraph.number_format(this.scale[4],c,f),null,g);if(k==5){RGraph.Text(d,h,b,e,a+0.2*l+this.halfTextHeight,RGraph.number_format(this.scale[3],c,f),null,g);RGraph.Text(d,h,b,e,a+0.6*l+this.halfTextHeight,RGraph.number_format(this.scale[1],c,f),null,g)}if(k>=3){RGraph.Text(d,h,b,e,a+0.4*l+this.halfTextHeight,RGraph.number_format(this.scale[2],c,f),null,g);RGraph.Text(d,h,b,e,a+0.8*l+this.halfTextHeight,RGraph.number_format(this.scale[0],
c,f),null,g)}if(k>=3){RGraph.Text(d,h,b,e,a+1.2*l+this.halfTextHeight,"-"+RGraph.number_format(this.scale[0],c,f),null,g);RGraph.Text(d,h,b,e,a+1.6*l+this.halfTextHeight,"-"+RGraph.number_format(this.scale[2],c,f),null,g)}if(k==5){RGraph.Text(d,h,b,e,a+1.4*l+this.halfTextHeight,"-"+RGraph.number_format(this.scale[1],c,f),null,g);RGraph.Text(d,h,b,e,a+1.8*l+this.halfTextHeight,"-"+RGraph.number_format(this.scale[3],c,f),null,g)}RGraph.Text(d,h,b,e,a+2*l+this.halfTextHeight,"-"+RGraph.number_format(this.scale[4]==
"1.0"?"1.0":this.scale[4],c,f),null,g);typeof this.Get("chart.ymin")=="number"&&RGraph.Text(d,h,b,e,this.canvas.height/2,RGraph.number_format(this.Get("chart.ymin").toFixed(this.Get("chart.scale.decimals")),c,f),"center",g)}else{RGraph.Text(d,h,b,e,a+this.halfTextHeight+0*(this.canvas.height-2*this.Get("chart.gutter")),RGraph.number_format(this.scale[4],c,f),null,g);if(k==5){RGraph.Text(d,h,b,e,a+this.halfTextHeight+0.6*(this.canvas.height-2*this.Get("chart.gutter")),RGraph.number_format(this.scale[1],
c,f),null,g);RGraph.Text(d,h,b,e,a+this.halfTextHeight+0.2*(this.canvas.height-2*this.Get("chart.gutter")),RGraph.number_format(this.scale[3],c,f),null,g)}if(k>=3){RGraph.Text(d,h,b,e,a+this.halfTextHeight+0.4*(this.canvas.height-2*this.Get("chart.gutter")),RGraph.number_format(this.scale[2],c,f),null,g);RGraph.Text(d,h,b,e,a+this.halfTextHeight+0.8*(this.canvas.height-2*this.Get("chart.gutter")),RGraph.number_format(this.scale[0],c,f),null,g)}typeof this.Get("chart.ymin")=="number"&&RGraph.Text(d,
h,b,e,this.canvas.height-a,RGraph.number_format(this.Get("chart.ymin").toFixed(this.Get("chart.scale.decimals")),c,f),"center",g)}}if(this.Get("chart.labels")){c=13;f=0;e=null;g="center";if(this.Get("chart.text.angle")==45||this.Get("chart.text.angle")==90){f=-1*this.Get("chart.text.angle");e="center";g="right";c=5}this.context.fillStyle=this.Get("chart.text.color");for(i=0;i<this.Get("chart.labels").length;++i)if(this.Get("chart.labels")[i]&&this.coords[i][0]){k=this.coords[i][0];if(this.Get("chart.labels").length!=
this.data[0].length)k=this.gutter+this.Get("chart.hmargin")+(this.canvas.width-2*this.gutter-2*this.Get("chart.hmargin"))*(i/(this.Get("chart.labels").length-1));RGraph.Text(d,h,b,k,this.canvas.height-a+c,String(this.Get("chart.labels")[i]),e,g,null,f)}}this.context.stroke()};
RGraph.Line.prototype.DrawLine=function(a,b,c){var f=false,d=0,e=0;this.context.lineWidth=1;var g=[],h=(this.canvas.width-2*this.Get("chart.hmargin")-2*this.gutter)/(a.length-1);for(k=0;k<a.length;k++){d=this.canvas.height-(a[k]-(a[k]>0?this.Get("chart.ymin"):-1*this.Get("chart.ymin")))/(this.max-this.min)*(this.canvas.height-2*this.gutter);if(this.Get("chart.xaxispos")=="center")d/=2;else if(this.Get("chart.xaxispos")=="bottom")d-=this.gutter;if(a[k]==null)d=null;this.context.lineCap="round";this.context.lineJoin=
"round";if(k>0)e+=h;else e=this.Get("chart.hmargin")+this.gutter;this.coords.push([e,d]);g.push([e,d])}this.context.stroke();document.all&&this.Get("chart.shadow")&&this.DrawIEShadow(g);this.context.beginPath();this.context.strokeStyle=c;this.context.fillStyle=c;h=this.Get("chart.stepped");for(var k=0;k<g.length;++k){e=g[k][0];d=g[k][1];a=g[k-1]?g[k-1][1]:null;var l=k+1==g.length;if(k==0||f||!d||!a){if(this.Get("chart.filled")&&!this.Get("chart.filled.range")){this.context.moveTo(e+1,this.canvas.height-
this.gutter-(this.Get("chart.xaxispos")=="center"?(this.canvas.height-2*this.gutter)/2:0)-1);this.context.lineTo(e+1,d)}else this.context.moveTo(e,d);f=false}else{h&&this.context.lineTo(e,g[k-1][1]);if(d>=this.gutter&&d<=this.canvas.height-this.gutter){if(l&&this.Get("chart.filled")&&!this.Get("chart.filled.range")&&this.Get("chart.yaxispos")=="right")e-=1;if(!h||!l)this.context.lineTo(e,d);f=false}else f=true}}if(this.Get("chart.filled")&&!this.Get("chart.filled.range")){this.Get("chart.fillstyle");
this.context.lineTo(e,this.canvas.height-this.gutter-1-+(this.Get("chart.xaxispos")=="center"?(this.canvas.height-2*this.gutter)/2:0));this.context.fillStyle=c;this.context.fill()}this.context.stroke();this.RedrawLine(g,b);this.context.stroke();for(k=0;k<g.length;++k){k=Number(k);if(this.Get("chart.tickmarks")!="endcircle"&&this.Get("chart.tickmarks")!="endsquare"&&this.Get("chart.tickmarks")!="filledendsquare"&&this.Get("chart.tickmarks")!="endtick"&&this.Get("chart.tickmarks")!="arrow"&&this.Get("chart.tickmarks")!=
"filledarrow"||k==0&&this.Get("chart.tickmarks")!="arrow"&&this.Get("chart.tickmarks")!="filledarrow"||k==g.length-1){c=k<=0?null:g[k-1][0];a=k<=0?null:g[k-1][1];this.DrawTick(g[k][0],g[k][1],b,false,c,a);this.Get("chart.stepped")&&g[k+1]&&this.Get("chart.tickmarks")!="endsquare"&&this.Get("chart.tickmarks")!="endcircle"&&this.Get("chart.tickmarks")!="endtick"&&this.DrawTick(g[k+1][0],g[k][1],b)}}this.context.beginPath();this.context.arc(this.canvas.width+50,this.canvas.height+50,2,0,6.38,1);if(this.Get("chart.tooltips")&&
this.Get("chart.tooltips").length){RGraph.Register(this);this.canvas.onmousemove=function(n){n=RGraph.FixEventObject(n);var m=n.target,o=m.getContext("2d"),p=m.__object__;RGraph.Register(p);var q=RGraph.getMouseXY(n),u=q[0];q=q[1];for(k=0;k<p.coords.length;++k){var t=k,r=p.coords[k][0],s=p.coords[k][1];if(u<=r+5&&u>=r-5&&q<=s+5&&q>=s-5&&p.Get("chart.tooltips")[k]){m.style.cursor=document.all?"hand":"pointer";if(RGraph.Registry.Get("chart.tooltip")&&RGraph.Registry.Get("chart.tooltip").__index__==
t)return;RGraph.Redraw();RGraph.Tooltip(m,p.Get("chart.tooltips")[t],n.pageX,n.pageY);RGraph.Registry.Get("chart.tooltip").__index__=Number(t);o.beginPath();o.moveTo(r,s);o.arc(r,s,2,0,6.28,0);o.strokeStyle="#999";o.fillStyle="white";o.stroke();o.fill();n.stopPropagation=true;n.cancelBubble=true;return}}m.style.cursor="default"}}else this.canvas.onmousemove=null};
RGraph.Line.prototype.DrawTick=function(a,b,c,f,d,e){var g=this.Get("chart.gutter");if(!(b==null||b>this.canvas.height-g||b<g)){this.context.beginPath();this.context.lineWidth=this.Get("chart.linewidth");this.context.strokeStyle=f?this.Get("chart.shadow.color"):this.context.strokeStyle;this.context.fillStyle=f?this.Get("chart.shadow.color"):this.context.strokeStyle;if(this.Get("chart.tickmarks")=="circle"||this.Get("chart.tickmarks")=="filledcircle"||this.Get("chart.tickmarks")=="endcircle"){if(this.Get("chart.tickmarks")==
"circle"||this.Get("chart.tickmarks")=="filledcircle"||this.Get("chart.tickmarks")=="endcircle"){this.context.beginPath();this.context.arc(a+0,b+0,this.Get("chart.ticksize"),0,360/(180/Math.PI),false);this.context.fillStyle=this.Get("chart.tickmarks")=="filledcircle"?f?this.Get("chart.shadow.color"):this.context.strokeStyle:f?this.Get("chart.shadow.color"):"white";this.context.fill();this.context.stroke()}}else if(this.Get("chart.tickmarks")=="halftick"){this.context.beginPath();this.context.moveTo(a,
b);this.context.lineTo(a,b+this.Get("chart.ticksize"));this.context.stroke()}else if(this.Get("chart.tickmarks")=="tick"){this.context.beginPath();this.context.moveTo(a,b-this.Get("chart.ticksize"));this.context.lineTo(a,b+this.Get("chart.ticksize"));this.context.stroke()}else if(this.Get("chart.tickmarks")=="endtick"){this.context.beginPath();this.context.moveTo(a,b-this.Get("chart.ticksize"));this.context.lineTo(a,b+this.Get("chart.ticksize"));this.context.stroke()}else if(this.Get("tickmarks")==
"cross"){this.context.beginPath();this.context.moveTo(a-this.Get("chart.ticksize"),b-this.Get("chart.ticksize"));this.context.lineTo(a+this.Get("chart.ticksize"),b+this.Get("chart.ticksize"));this.context.moveTo(a+this.Get("chart.ticksize"),b-this.Get("chart.ticksize"));this.context.lineTo(a-this.Get("chart.ticksize"),b+this.Get("chart.ticksize"));this.context.stroke()}else if(this.Get("chart.tickmarks")=="borderedcircle"||this.Get("chart.tickmarks")=="dot"){this.context.lineWidth=1;this.context.strokeStyle=
this.Get("chart.tickmarks.dot.color");this.context.fillStyle=this.Get("chart.tickmarks.dot.color");this.context.beginPath();this.context.arc(a,b,this.Get("chart.ticksize"),0,360/(180/Math.PI),false);this.context.closePath();this.context.fill();this.context.stroke();this.context.beginPath();this.context.fillStyle=c;this.context.strokeStyle=c;this.context.arc(a,b,this.Get("chart.ticksize")-2,0,360/(180/Math.PI),false);this.context.closePath();this.context.fill();this.context.stroke()}else if(this.Get("chart.tickmarks")==
"square"||this.Get("chart.tickmarks")=="filledsquare"||this.Get("chart.tickmarks")=="endsquare"||this.Get("chart.tickmarks")=="filledendsquare"){this.context.fillStyle="white";this.context.strokeStyle=this.context.strokeStyle;this.context.beginPath();this.context.strokeRect(a-this.Get("chart.ticksize"),b-this.Get("chart.ticksize"),this.Get("chart.ticksize")*2,this.Get("chart.ticksize")*2);if(this.Get("chart.tickmarks")=="filledsquare"||this.Get("chart.tickmarks")=="filledendsquare"){this.context.fillStyle=
f?this.Get("chart.shadow.color"):this.context.strokeStyle;this.context.fillRect(a-this.Get("chart.ticksize"),b-this.Get("chart.ticksize"),this.Get("chart.ticksize")*2,this.Get("chart.ticksize")*2)}else if(this.Get("chart.tickmarks")=="square"||this.Get("chart.tickmarks")=="endsquare"){this.context.fillStyle=f?this.Get("chart.shadow.color"):"white";this.context.fillRect(a-this.Get("chart.ticksize")+1,b-this.Get("chart.ticksize")+1,this.Get("chart.ticksize")*2-2,this.Get("chart.ticksize")*2-2)}this.context.stroke();
this.context.fill()}else if(this.Get("chart.tickmarks")=="filledarrow"){c=Math.abs(a-d);f=Math.abs(b-e);e=b<e?Math.atan(c/f)+1.57:Math.atan(f/c)+3.14;this.context.beginPath();this.context.moveTo(a,b);this.context.arc(a,b,7,e-0.5,e+0.5,false);this.context.closePath();this.context.stroke();this.context.fill()}else if(this.Get("chart.tickmarks")=="arrow"){c=Math.abs(a-d);f=Math.abs(b-e);e=b<e?Math.atan(c/f)+1.57:Math.atan(f/c)+3.14;this.context.beginPath();this.context.moveTo(a,b);this.context.arc(a,
b,7,e-0.5-(document.all?0.1:0),e-0.4,false);this.context.moveTo(a,b);this.context.arc(a,b,7,e+0.5+(document.all?0.1:0),e+0.5,true);this.context.stroke()}}};
RGraph.Line.prototype.DrawRange=function(){if(this.Get("chart.filled.range")&&this.Get("chart.filled")){this.context.beginPath();this.context.fillStyle=this.Get("chart.fillstyle");this.context.strokeStyle=this.Get("chart.fillstyle");this.context.lineWidth=1;for(var a=this.coords.length/2,b=0;b<a;++b)b==0?this.context.moveTo(this.coords[b][0],this.coords[b][1]):this.context.lineTo(this.coords[b][0],this.coords[b][1]);for(b=this.coords.length-1;b>=a;--b)this.context.lineTo(this.coords[b][0],this.coords[b][1]);
this.context.stroke();this.context.fill()}};
RGraph.Line.prototype.RedrawLine=function(a,b){this.context.beginPath();this.context.strokeStyle=typeof b=="object"&&b?b[0]:b;this.context.lineWidth=this.Get("chart.linewidth");for(var c=a.length,f=this.gutter,d=0;d<c;++d){var e=this.canvas.width,g=this.canvas.height,h=a[d][1];if(d>0)var k=a[d-1][0],l=a[d-1][1];if(d==0&&a[d]||h<f||h>g-f||d>0&&k>e-f||d>0&&l>g-f)this.context.moveTo(a[d][0],a[d][1]);else{this.Get("chart.stepped")&&d>0&&this.context.lineTo(a[d][0],a[d-1][1]);if(!this.Get("chart.stepped")||
d<a.length-1)this.context.lineTo(a[d][0],a[d][1])}}if(this.Get("chart.colors.alternate")&&typeof b=="object"&&b[0]&&b[1])for(d=1;d<c;++d){k=a[d-1][0];l=a[d-1][1];this.context.beginPath();this.context.strokeStyle=b[a[d][1]<l?0:1];this.context.lineWidth=this.Get("chart.linewidth");this.context.moveTo(k,l);this.context.lineTo(a[d][0],a[d][1]);this.context.stroke()}};
RGraph.Line.prototype.DrawIEShadow=function(a){var b=this.Get("chart.shadow.offsetx"),c=this.Get("chart.shadow.offsety");this.Get("chart.shadow.color");this.context.lineWidth=this.Get("chart.linewidth");this.context.strokeStyle=this.Get("chart.shadow.color");this.context.beginPath();for(var f=0;f<a.length;++f)f==0?this.context.moveTo(a[f][0]+b,a[f][1]+c):this.context.lineTo(a[f][0]+b,a[f][1]+c);this.context.stroke()};